### PR TITLE
map better

### PR DESCRIPTION
**Pull request by corybenton**
map will only show up to 5 pins
when remove a favorite the pin goes away

### CODE REVIEW

**Comment by Conartisttt** [comment]
Remove cards function on liked page doesn't seem to be working correctly...is it working on your end?

**Comment by corybenton** [comment]
Yes.  I commented out a line that I thought was superfluous, but it wasn't.  I uncommented it.

**Review by elmiquea — COMMENTED** [review]
It looks good!

**Review by elmiquea — COMMENTED** [review]
It looks good!

**Review by Conartisttt — APPROVED** [review]
LGTM

**Pull request merged**
