### PR TITLE
add starter files to project

### PR DESCRIPTION
**Pull request by Conartisttt**

### CODE REVIEW

**Review by corybenton — COMMENTED** [review]
First sentence of features mentions weather dashboard.  That should be changed.

**Comment by Conartisttt** [comment]
> First sentence of features mentions weather dashboard.  That should be changed.

Oooo good catch. On it!
P.S. - do I make these changes and just submit a completely new pull request?

**Comment by corybenton** [comment]
not sure. can you change it in the codespace?

**Comment by Conartisttt** [comment]
> not sure. can you change it in the codespace?

Got it! Yes I was able to just edit the file from here...cool.

**Pull request merged**
