### PR TITLE
Basic features

### PR DESCRIPTION
**Pull request by Conartisttt**
- created like page (second html document)
- dynamically generated brewery list to html page based on search of zip or IP
- added data of each brewery to each like button so that it can be used by event listeners (local storage)
- added styling
- added classes to elements based on https://github.com/elmiquea/Project-1/pull/6

### CODE REVIEW

**Comment by corybenton** [comment]
Isn't jquery supposed to go before script.js? Are we even using jquery?  Otherwise it LGTM.

**Comment by corybenton** [comment]
both html pages had jquery right?

**Comment by Conartisttt** [comment]
> both html pages had jquery right?

Good call.

**Comment by corybenton** [comment]
I noticed one more thing.  Why put the favebox attributes as street city and state instead of just using address which combined all three already?

**Comment by Conartisttt** [comment]
> I noticed one more thing.  Why put the favebox attributes as street city and state instead of just using address which combined all three already?

I wish just passing all the data out of the function and storing it in the button, was going to let you handle the format of how you wanted it to be displayed afterwards

**Comment by corybenton** [comment]
That works, but I'd just be doing the same thing you already did for address.textContent when I redisplay it.  Seems easier to have 3 variables instead of 5.

**Review by corybenton — APPROVED** [review]
LGTM

**Pull request merged**
